ComplementaryData/annotation/humanGEMMetAssoc.JSON
ComplementaryData/annotation/humanGEMRxnAssoc.JSON
ComplementaryScripts/Functions/annotateModel.m
ComplementaryScripts/GPRs/translateGrRules.m

The main component of this PR is a new function `annotateModel` that adds reaction, metabolite, and/or gene annotation information (i.e., alternate/external IDs) to the model. 
The function retrieves reaction and metabolite annotation information ifrom the `humanGEMRxnAssoc.JSON` and `humanGEMMetAssoc.JSON` files, respectively, whereas gene annotation information is retrieved with the help of the `translateGrRules` function, which uses the `ensembl_ID_mapping.tsv` file.
The retrieved annotation information is added to the corresponding model MIRIAM fields (`rxnMiriams`, `metMiriams`, `geneMiriams`) and/or as individual model fields (e.g., `rxnKEGGID`, `metChEBIID`, etc.).
**Renaming MetaNetX fields**
Here it is proposed to re-name the `rxnMNXID` and `metMNXID` fields to `rxnMetaNetXID` …

Annotation of model rxns, mets, and genes

---

ComplementaryScripts/Functions/exportHumanGEM.m

The `exportHumanGEM` function is updated with the following two changes:
- Use `annotateModel` function to add annotations to model prior to exporting to SBML.
- Remove inactivated reactions (those with `lb == ub == 0`) prior to exporting to SBML, as some software/tools treat this as active reactions.

feat: add model annotations prior to exporting SBML

---

ComplementaryScripts/modelCuration/removeConflictingInchiStrings.m
ComplementaryScripts/modelCuration/updateModelInchiStrings.m

Many of the entries in the `inchis` field are out of sync with the `metFormulas` field (see issue #145).
This PR introduces a new function `removeConflictingInchiStrings` that compares all non-empty `inchis` entries with their corresponding entry in `metFormulas` and deletes the `inchis` entry if they disagree. This function (or some variant) could be re-run on the model anytime the `metFormulas` or `inchis` fields are modified to ensure that they remain synced.
The model can be updated by simply running the following command:
`ihuman = removeConflictingInchiStrings(ihuman);`

fix: remove inchi entries that conflict with metFormulas

---

ComplementaryScripts/Functions/tINIT/getINITModel2.m

This PR fixes a small bug in `getINITModel2` where metabolites defined as inputs or outputs to metabolic tasks would be removed and then re-added to the model with a different ID. The function now prevents the removal of task-associated metabolites from the start, to avoid confusion with re-named metabolites in the final model.

fix: getINITModel2

---

README.md

The README file is updated to include information about the new [Human-GEM user guide](https://sysbiochalmers.github.io/Human-GEM-guide/).
I also suggest that we set the "website" of the Human-GEM repository (shown at the top of the main page next to the repo description) to this guide, to make it even easier for people to find.

update README with references/links to the Human-GEM user guide

---

code/io/importHumanYaml.m
code/io/writeHumanYaml.m
code/test/testYamlConversion.m

This PR is to address the issue raised in #169
* The `Yaml` file is updated by systematically enclosing string elements with double quote, through the modified `writeHumanYaml` function
* `importHumanYaml` is adapted to the addition of double quote in `Yaml` format
* `testYamlConversion` is simplified by removing the input value and turning off notifications
* Note that this PR has no effect on the model content, as well as file formats other than `Yaml`

fix: systematically add double quote to string elements in Yaml file

---

.github/workflows/yaml-validation.yml
code/io/importHumanYaml.m
code/io/writeHumanYaml.m
code/test/testYamlConversion.m

This PR addresses all yaml indentation issues from #169 and adds a GitHub Action to run `yamllint` on PRs to `master` and `devel`, and pushes to `devel`. The `yamllint` configuration `{extends: default, rules: {line-length: disable}}`, which, unlike `extends: relaxed` means most problems will result in errors, [as per the documentation](https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration). The `line-length` is disabled because it's unlikely this will be addressed.
I've ran `testYamlConversion.m` on the new yaml but nothing more.
Edit: Cobrapy import has also been added to the workflow.

feat: yaml worflow

---

.github/workflows/yaml-validation.yml

There seems to be a problem in recent runs of the Actions. `swiglpk` doesn't get installed because of a missing dependency `glpsol`. By adding that dependency, we can hopefully get the workflow to work again.

fix: add glpk as dependency for swiglpk

---

code/io/exportHumanGEM.m

Fix issues found in the InChI strings stored in the YAML format of the model:
- **716** missing prefixes on InChI string (must start with `InChI=`)
- duplicated InChI on **2** metabolites having different names
- **338** missing InChI string for some of the compartmentalized metabolites
- **2** Inconsistencies between `inchi formula` and `metFormula`
Fixes #220 

Fix: invalid InChI strings stored in YAML

---

code/evalGeneEssentialityPred.m

Added a new function `evalGeneEssentialityPred` to assess gene essentiality predictions made by a GEM. Given a GEM, a list of metabolic task(s), and a cell array of experimentally-based gene essentiality information, the function will quantify the GEM's ability to predict the essential genes using several metrics:
- sensitivity
- specificity
- accuracy
- F1 statistic
- Matthew's Correlation Coefficient (MCC)
- hypergeometric test p-value
View the function header for further detail.

Feat: Evaluation of GEM-based gene essentiality predictions

---

.deprecated/code/modelCuration/GPRs/combineModelGPRs.m
.deprecated/code/modelCuration/GPRs/combineModelGPRsScript.m
.deprecated/code/modelCuration/MetAssociation/HMR_master_met_curation.m
.deprecated/code/modelCuration/modelIntegration/integrateRecon3DToHMR.m
.github/CONTRIBUTING.md
.github/issue_template.md
.github/workflows/yaml-validation.yml
.standard-GEM.md
README.md
code/io/increaseHumanGEMVersion.m

This PR follows the rename of the `master` branch to `main` as discussed in https://github.com/SysBioChalmers/Human-GEM/discussions/226, updating all the references. Moreover, it also replaces some other occurrences of the word `master`.

chore: master renamed main

---

.github/workflows/yaml-conversion.yml
code/test/testYamlConversion.m

As mention in #285 (and most likely elsewhere), this PR introduces a GH Action for testing the `yaml` conversion workflow (to and from Matlab).

feat: action for testing yaml conversion

---

code/GPRs/fetch_ensembl_gene_annotations.py

Fix `fetch_ensembl_gene_annotations.py` script to retrieve annotations for genes without symbols or ENSP ID. The script can also show error messages for deprecated gene IDs, and list the replacement IDs provided by Ensembl. The deprecated IDs must still be manually fixed. See #278 for additional information.

Ensembl annotations query

---

code/test/sanityCheck.py

* Adjust `sanityCheck` script to detect the cases of reusing deprecated reaction and metabolite identifiers, as discussed in #265.

feat: enable GH actions to report reusing of deprecated reaction and metabolite identifiers

---

.all-contributorsrc
README.md

This PR implements  [all-contributors](https://allcontributors.org/) by
[Here is a direct link to the preview of the README file in this branch](https://github.com/SysBioChalmers/Human-GEM/blob/feat/all-contributors/README.md). 
In addition:
After merging this PR:

feat: adopt all-contributors

---

.github/CONTRIBUTING.md
README.md
model/README.md

* improve the `contributing guidelines` in Human-GEM
* remove the section of git commands, which are no longer necessary after the implementation of yaml workflow
* increase visibility of `contributing` section in README by moving it to top 
* move annotation file details from main README to that under `model` directory

doc: simplify `contributing guidelines` and improve the visibility to contributors

---

.github/workflows/yaml-validation.yml

This PR aims to refactor the GitHub actions by replacing the direct usage of Python and installation of packages with the `opencobra/memote` container from DockerHub. In doing so, we are using a more robust and reproducible setup for the GH Actions. Moreover, with increased confidence in this Docker image, we can begin thinking about integrating `memote` via a new GH Action.

refactor: GitHub actions

---

code/tINIT/getINITModel2.m

As stated in #355, some of the comments and error messages in the `getINITModel2` function referenced "exchange metabolites" and suggested using the "importModel" function to add/remove such metabolites. This PR renames occurrences of "exchange metabolites" to the more often used (in this repo) "boundary metabolites", and instead suggests the use of the `addBoundaryMets` function to add these metabolites to a model.

doc: tINIT rename 'exchange metabolites' to 'boundary metabolites'

---

code/curateReactionNames.py

This PR resolves #181 by taking 2000 reaction names from KEGG (the first supplied). The work was done fully scripted on [Google Colab](https://colab.research.google.com/drive/17X0Qx0H4pwjZjLLWHnpp5ac2daH9hOxs?usp=sharing) and also moved to the `/code` folder.

feat: add reaction names from KEGG

---

code/annotateGEM.m
code/gapfill4EssentialTasks.m
code/getModelFromOrthology.m

* This PR refactors code for updating animal GEMs, and resolves issues reported in Mouse-GEM:
- change metabolic task file format from `xlsx` to `txt`
- inactivate human biomass reaction (MAR13082), as suggested in Mouse-GEM [PR #11](https://github.com/SysBioChalmers/Mouse-GEM/issues/11) 
- add proper LB and UB values to `annotation` field, as reported in Mouse-GEM [PR #12](https://github.com/SysBioChalmers/Mouse-GEM/issues/12) 
- turn `annotateGEM` into a more generic function, as discussed in #380

fix: resolves issues reported in animal GEM repos

---

code/io/importYaml.m

- refactor:
- `importYaml` speed improvement, contributing to #387
On my PC, `importYaml('../../model/Human-GEM.yml');` tooks 248 seconds before the change and 12 seconds after the change.

refactor: speed up writing model fields

---

code/modelCuration/removeDuplicateRxns_issue345.m

Continues the work in #403 which addressed #345.
This PR merges information from the `eccodes` and `rxnReferences` model fields from the removed duplicate reactions with those of the retained reactions.
**Note:** I also inspected the `subSystems`, `rxnNames`, `rxnNotes`, and `rxnConfidenceScores` fields, but these were either identical or were not meaningful/appropriate to merge between the reaction pairs.

Fix: Amend #403 by merging additional model fields from duplicated rxns

---

code/io/importYaml.m

The `importYaml` function defines and creates a set of model fields at the start of import, which means that if some fields are missing from the `.yml` file, the corresponding fields in the Matlab structure will be empty. Since some functions expect fields to be of a certain length (e.g., those relating to metabolites, genes, and reactions), empty fields may cause errors in those functions.
This PR implements a change in the `importYaml` function that checks if any model fields are still empty at the end of the import process, and removes those fields. A few exceptions are included to avoid removing some fields which are OK to be empty (`description`, `version`).
This PR also addresses an [Issue](https://github.com/SysBioChalmers/Mouse-GEM/issues/17) in the Mouse-GEM repository.
**I …

fix: remove some empty fields from imported yaml model

---

code/tINIT/prepHumanModelForftINIT.m

This PR fixes issue #401 and now allows for specifying the paths to the tasks and reactions.tsv. This is good when using the code for for example Mouse-GEM.
prepHumanModelForftINIT supports other models such as Mouse-GEM - the paths to relevant files could not be specified earlier.

feat: prepHumanModelForftINIT with paths

---

code/io/exportYaml.m
code/io/importYaml.m

This PR aims to move forward to community curation
- ~~empty~~ remove `authors`, `email`, and `organization` fields in code and Yaml file
- use GitHub to count contributors 

style: move from lab-based development to community curation

---

code/io/importYaml.m

- fix:
- `importYaml` fatal bug (solves #614)
- `importYaml` makes `model.metCharges` as double, not int64 (see [RAVEN](https://github.com/SysBioChalmers/RAVEN/wiki/RAVEN-Model-Structure) and [COBRA](https://github.com/opencobra/cobratoolbox/blob/master/docs/source/notes/COBRAModelFields.md) model fields definitions)

fix: fatal importYaml bug

---

code/io/importYaml.m
code/test/testYamlConversion.m

This PR is to fix only the bug found in Yaml file, as reported in #628. In the meantime, another PR #635 is to fix error of GH workflow test

fix-add a error report in the import/export cycle

---

.github/workflows/yaml-validation.yml
code/test/memoteTest.py

This PR resolves #671 by introducing a basic MEMOTE tests in the `yaml-validation` workflow, and another new test that makes sure all reactions have at least one metabolite.
**Notes**
This PR is not aimed directly at `develop`, but at another branch where a bug was artificially introduced. The aim of this PR is then to capture this failure, then merge this PR. Finally, after reverting the commit introducing the bug, the `fix/importExportCycle`  will have valid content with improved workflows.

feat: add basic memote tests

---

.github/workflows/check-metabolictasks.yml
.github/workflows/yaml-conversion.yml
.github/workflows/yaml-validation.yml
code/io/importYaml.m
code/test/memoteTest.py
code/test/testMetabolicTasks.m
code/test/testYamlConversion.m

This PR is continuing #629 aimed to fix the GH workflow test of the import-export cycle, thus resolving #628.

fix: GH workflow test

---

code/addMetabolicNetwork.m
code/updateAnimalGEM.m

This PR improves animal GEM updating pipeline:
- sync `geneShortNames` field (introduced by #539) by padding with empty elements in function `addMetabolicNetwork`
- enable `updateAnimalGEM` with option of reusing Human-GEM biomass equation

fix: refine animal GEM updating pipeline

---

data/metabolicTasks/metabolicTasks_CellfieConsensus.txt

This is a simple fix that follows the previous commits (https://github.com/exaexa/Human-GEM/commit/8182ade485807697c2e79cf12b2a89f91e5f20cb) to remove old name for GAP[c].

fix: update name for GAP in CellfieConsensus metabolic tasks

---

data/metabolicTasks/metabolicTasks_CellfieConsensus.txt

This replaces a few nonexistent metabolites following the advice from the comments in #696 (mainly https://github.com/SysBioChalmers/Human-GEM/pull/696#issuecomment-1698627018 ).
The glycogenin in question should most likely be this thing: http://bigg.ucsd.edu/models/universal/metabolites/Tyr_ggn but the metabolite is missing in the model, so I went with the "closest approximation". This will require more thorough changes if we should add it instead.
cc @migp11

Fix the `NA[c]` metabolite in Cellfile metabolic tasks

---

code/modelCuration/reportPeroxGenesFromBetaoxidationGPRsInMito.py

according to the table reported by #767, this PR remove genes expressed only in peroxisome from GPRs of beta-oxidation reactions in mitochondria. The specific changes are:
- add [code](https://github.com/SysBioChalmers/Human-GEM/pull/770/files#diff-186bf4f9b5d35a79293ff1230e7cd76d9a16b2fcb2bd2dad9e1cabe2557dac1f), which is inspired by #746, for checking genes with mismatched compartment assignment
- remove ENSG00000115425 from MAR02028, MAR02148, MAR02149, MAR02183, MAR02187, MAR02207, respectively
- remove ENSG00000113790 from MAR03297, MAR03374, MAR03378, MAR03379, respectively
- remove ENSG00000060971 from MAR02381 and modify the GPR to `ENSG00000138029 or ENSG00000167315`, as reported in #759
Note that modifications to MAR03269 and MAR03380 had already been addressed by #760
**I …

fix: remove genes only expressed in peroxisome from beta-oxidation reactions in mitochondria

---

.github/workflows/check-metabolictasks.yml
.github/workflows/yaml-conversion.yml
.github/workflows/yaml-validation.yml

This PR aims to resolve the Node 16 warning generated when running GH Actions, as shown below:

chore: update actions

---

data/metabolicTasks/metabolicTasks_Full.txt

As proposed in #828:
- Rename heneicosanoic acid to heneicosanoic acid in `metabolicTasks_Full.txt`

fix: heneicosanoic acid in metabolicTasks_Full.txt

---

.github/pull_request_template.md

The PR template now clarifies that *squash-merge* should be used for merges to `develop`, while merges to `main` should be resolved as *merge commit*. The checkboxes help to remember this, but the actual choice of merge type can only be selected when the actual merge is made. The reason for using *squash-merge* to `develop` is to somewhat reduce the clutter in the repository's git history.

feat: PR template mentions merge type

---

data/testResults/README.md

As proposed in #864 
- Remove `ENSG00000147576`, `ENSG00000196616` from MAR07038;
- Remove `ENSG00000108242` from MAR07053;
- Remove `ENSG00000117594` from MAR07059;
- Remove `ENSG00000108242` from MAR07096;
- Remove `ENSG00000117592` from MAR06536;
- Remove `ENSG00000184254`, `ENSG00000006534` from MAR09569;
- Remove `ENSG00000130508` from MAR06535;
- Remove `ENSG00000108242` from MAR07019;
- Remove `ENSG00000108242` from MAR07021;
- Remove `ENSG00000186377`, `ENSG00000137869` from MAR04019;
- Remove `ENSG00000186160`, `ENSG00000186377` from MAR04041;
- Remove `ENSG00000108242` from MAR04051.

fix-GPR curation for Xenobiotics metabolism

---

data/testResults/README.md

As proposed in #892 
- Remove `ENSG00000104331` from MAR04187;
- Remove `ENSG00000108602` from MAR04842;
- Remove `ENSG00000204386` from MAR07530;
- Remove `ENSG00000204386` from MAR07542;
- Remove `ENSG00000204386` from MAR07560;
- Remove `ENSG00000204386` from MAR07526;
- Remove `ENSG00000204386` from MAR07547;
- Remove `ENSG00000135702` from MAR07369;
- Remove `ENSG00000106304` from MAR07503.

Fix: GPR curation for Sulfur metabolism

---

data/testResults/README.md

As proposed in #860 
- Remove `ENSG00000101577`, `ENSG00000132793`, `ENSG00000134324` from MAR00746;
- Remove `ENSG00000102595`, `ENSG00000175711`, `ENSG00000147162`, `ENSG00000180549`, `ENSG00000069943`, `ENSG00000172461`, `ENSG00000198488`, `ENSG00000170340`, `ENSG00000196371`, `ENSG00000136731`, `ENSG00000172728`, `ENSG00000085998`, `ENSG00000167889` from MAR00765;
- Remove `ENSG00000101577` from MAR00767;
- Remove `ENSG00000134324` from MAR00775;
- Remove `ENSG00000179913` from MAR08152;
- Remove `ENSG00000179913` from MAR08173;
- Remove `ENSG00000179913` from MAR08249.

Fix: GPR curation for Sphingolipid metabolism

---

data/testResults/README.md

As proposed in #851 :
- Change the GPR of MAR01927 as `ENSG00000140459 or ENSG00000138061`, and add `PMID:39395524` as additional references;
- Change the GPR of MAR02029 as `ENSG00000137869`, and add `PMID:34095690` as additional references;
- Change the GPR of MAR02030 as `ENSG00000137869`, and add `PMID:34095690` as additional references;
- Change the GPR of MAR02031 as `ENSG00000137869`, and add `PMID:34095690` as additional references;
- Change the GPR of MAR02032 as `ENSG00000137869`, and add `PMID:34095690` as additional references;
- Change the GPR of MAR02033 as `ENSG00000137869`, and add `PMID:34095690` as additional references;
- Change the GPR of MAR02034 as `ENSG00000137869`, and add `PMID:34095690` as additional references;
- Change the GPR of MAR02038 as `ENSG00000101846`, …

Fix: GPR curation for Estrogen and Steroid metabolism
